name: Deploy-Webapp
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    
    - name: install emscripten
      run: git clone https://github.com/emscripten-core/emsdk.git && emsdk/emsdk install 3.1.49 && emsdk/emsdk activate 3.1.49 && source emsdk/emsdk_env.sh

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=On -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake 
    
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --target aoc-2024-web -j8

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/bin/aoc-2024-www # The folder the action should deploy.
